version: '3.8'

services:
  wrk:
    image: openeuler/wrk:latest
    network_mode: host  # This allows WRK to access services on host machine ports
    volumes:
      - ./lua_scripts:/scripts:ro  # Mount lua scripts directory
    working_dir: /scripts
    tty: true  # Allocate a pseudo-TTY
    init: true  # Use init process
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
