version: '3.9'
services:
  flask:
    build: ./flask
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - db
  django:
    build: ./django
    env_file:
      - .env
    ports:
      - "8002:8002"
    depends_on:
      - db
  fastapi:
    build: ./fastapi
    env_file:
      - .env
    ports:
      - "8003:8003"
    depends_on:
      - db
  express:
    build: ./express
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
  gin:
    build: ./gin
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
