[project]
name = "pycon2025-benchmarking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.1.1",
    "python-on-whales>=0.78.0",
]
