# Generated by Django 5.2.4 on 2025-07-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=16)),
                ('stock', models.IntegerField()),
                ('ean', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('availability', models.CharField(max_length=32)),
                ('internal_id', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
    ]
